### ISSUE TITLE
module 'recmetrics' has no attribute 'prediction_coverage'

### ISSUE THREAD

**Issue by rhkaz** [statisticianinstilettos/recmetrics#25]
Hi there 
I am trying to run example notebook. But I am getting 'module 'recmetrics' has no attribute 'prediction_coverage'' and "attribute error: module 'recmetrics' has no attribute 'catalog_coverage'"

any pointer or suggestion.

Thanks in advance

**Comment by itsoum** [comment]
Hello @rhkaz ,

I contributed the two above mentioned different versions of coverage metric at October of 2019 when @statisticianinstilettos accepted and merged these pull request.
If you have used `pip install recmetrics` in order to install the recmetrics probably your version is not aligned with the updated github repository version given that [last realease on pypi is  Mar 5, 2019](https://pypi.org/project/recmetrics/).
So, you should install manually recmetrics from github.

@statisticianinstilettos maybe you sould update the release.

Ilias

**Comment by gregwchase** [comment]
Fixed in #26
